-- =============================================================================
-- 68 — An email with nothing left to say
--
-- The outbox has had two ways for a message to end without being sent:
-- `failed`, which means the provider or the network refused it, and
-- `suppressed`, which means the address was off-limits before anyone tried.
-- Migration 69 retries in place on the same row, and that surfaces a third
-- ending the first two do not describe: by the time the retry comes round
-- there is nothing to send. The recipient switched the notification off, the
-- application was withdrawn, the listing was deleted, or a newer message about
-- the same thing already went out under a different key.
--
-- Recording that as `failed` would put it in the dead-letter view as if
-- something had gone wrong, and an admin would requeue it to be told the same
-- thing again. Recording it as `sent` would be a lie the delivery dashboard
-- repeats. So it gets its own word: cancelled — looked at, nothing to do,
-- finished.
--
-- Alone in this file, and it has to be: Postgres will not let a transaction
-- use an enum value that the same transaction added, and db-push.mjs and the
-- test harness each run one migration file as one transaction. Migration 69
-- backfills rows into this value and writes it from two functions, so it must
-- already be committed by then. Migrations 21 and 51 split a pair for the
-- same reason.
-- =============================================================================

alter type email_status add value if not exists 'cancelled';
